### ISSUE TITLE
Yahoo Finance should be updated again

### ISSUE THREAD

**Issue by leeschmalz** [lavolp3/MMM-AVStock#76]
this api call fails with the current version:
stock.quotes = await yfinance2.quoteSummary(symbols[i], {modules: ['price']});

should be updated to version 2.11.3

see discussion: https://github.com/gadicc/node-yahoo-finance2/issues/764

**Comment by lavolp3** [comment]
I have pushed a force to yfinance2 api v. 2.11.3

Please update:
```
git pull
npm install
```
and let me know if it works.

Thanks!

**Comment by leeschmalz** [comment]
I am running master branch, updating locally to 2.11.3 worked for me. it looks like your push was to "yfinance" branch, which contains other changes that I have not tested.

**Comment by rmcelwee** [comment]
This did NOT fix it for me:
git pull
npm install


This DID fix it. Thanks again for a great module and the help to keep it running!
rm -r node_modules
rm package-lock.json
git pull
npm install

**Comment by jmslln** [comment]
I was seeing this in the log:
_[2024-06-05 12:56:33.703] [LOG]   MMM-AVStock:  Error: Unsupported redirect to https://finance.yahoo.com/quote/AAPL/, please report.
    at /home/pi/MagicMirror/modules/MMM-AVStock/node_modules/yahoo-finance2/dist/cjs/src/lib/getCrumb.js:103:23
    at Generator.next (<anonymous>)
    at fulfilled (/home/pi/MagicMirror/modules/MMM-AVStock/node_modules/yahoo-finance2/dist/cjs/src/lib/getCrumb.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95_:5)

the advice from rmcelwee worked for me -  thanks to both of you for keeping this module active

**Comment by lavolp3** [comment]
> I am running master branch, updating locally to 2.11.3 worked for me. it looks like your push was to "yfinance" branch, which contains other changes that I have not tested.

This is right. I need to push the yfinance branch then it works how I described. Will do this tonight.

**Comment by lavolp3** [comment]
2 weeks late but has been pushed now. Closing this as resolved.

**Comment by JATINMOUR** [comment]
![Screenshot 2024-09-08 141319](https://github.com/user-attachments/assets/c5c36ab3-c6ed-44b8-87c7-4ac7946722c5)

anyone can help me
